<?php
/**
 * WP Emoji2 Docomo emoji map
 *
 * Decimal => Unicode へのマッピング
 * 画像のファイル名などのマップに使う
 */
return array(
	"d001" => array( "img" => "sun.gif", "alt" => "晴れ" ),
	"d002" => array( "img" => "cloud.gif", "alt" => "曇り" ),
	"d003" => array( "img" => "rain.gif", "alt" => "雨" ),
	"d004" => array( "img" => "snow.gif", "alt" => "雪 " ),
	"d005" => array( "img" => "thunder.gif", "alt" => "雷" ),
	"d006" => array( "img" => "typhoon.gif", "alt" => "台風" ),
	"d007" => array( "img" => "mist.gif", "alt" => "霧" ),
	"d008" => array( "img" => "sprinkle.gif", "alt" => "小雨" ),
	"d009" => array( "img" => "aries.gif", "alt" => "牡羊座" ),
	"d010" => array( "img" => "taurus.gif", "alt" => "牡牛座" ),
	"d011" => array( "img" => "gemini.gif", "alt" => "双子座" ),
	"d012" => array( "img" => "cancer.gif", "alt" => "蟹座" ),
	"d013" => array( "img" => "leo.gif", "alt" => "獅子座" ),
	"d014" => array( "img" => "virgo.gif", "alt" => "乙女座" ),
	"d015" => array( "img" => "libra.gif", "alt" => "天秤座" ),
	"d016" => array( "img" => "scorpius.gif", "alt" => "蠍座" ),
	"d017" => array( "img" => "sagittarius.gif", "alt" => "射手座" ),
	"d018" => array( "img" => "capricornus.gif", "alt" => "山羊座" ),
	"d019" => array( "img" => "aquarius.gif", "alt" => "水瓶座" ),
	"d020" => array( "img" => "pisces.gif", "alt" => "魚座" ),
	"d021" => array( "img" => "sports.gif", "alt" => "スポーツ" ),
	"d022" => array( "img" => "baseball.gif", "alt" => "野球" ),
	"d023" => array( "img" => "golf.gif", "alt" => "ゴルフ" ),
	"d024" => array( "img" => "tennis.gif", "alt" => "テニス" ),
	"d025" => array( "img" => "soccer.gif", "alt" => "サッカー" ),
	"d026" => array( "img" => "ski.gif", "alt" => "スキー" ),
	"d027" => array( "img" => "basketball.gif", "alt" => "バスケットボール" ),
	"d028" => array( "img" => "motorsports.gif", "alt" => "モータースポーツ (チェッカーフラッグ)" ),
	"d029" => array( "img" => "pocketbell.gif", "alt" => "ポケットベル" ),
	"d030" => array( "img" => "train.gif", "alt" => "電車" ),
	"d031" => array( "img" => "subway.gif", "alt" => "地下鉄" ),
	"d032" => array( "img" => "bullettrain.gif", "alt" => "新幹線" ),
	"d033" => array( "img" => "car.gif", "alt" => "車 (セダン)" ),
	"d034" => array( "img" => "rvcar.gif", "alt" => "車 (RV)" ),
	"d035" => array( "img" => "bus.gif", "alt" => "バス" ),
	"d036" => array( "img" => "ship.gif", "alt" => "船" ),
	"d037" => array( "img" => "airplane.gif", "alt" => "飛行機" ),
	"d038" => array( "img" => "house.gif", "alt" => "家" ),
	"d039" => array( "img" => "building.gif", "alt" => "ビル" ),
	"d040" => array( "img" => "postoffice.gif", "alt" => "郵便局" ),
	"d041" => array( "img" => "hospital.gif", "alt" => "病院" ),
	"d042" => array( "img" => "bank.gif", "alt" => "銀行" ),
	"d043" => array( "img" => "atm.gif", "alt" => "ATM" ),
	"d044" => array( "img" => "hotel.gif", "alt" => "ホテル" ),
	"d045" => array( "img" => "24hours.gif", "alt" => "コンビニ" ),
	"d046" => array( "img" => "gasstation.gif", "alt" => "ガソリンスタンド" ),
	"d047" => array( "img" => "parking.gif", "alt" => "駐車場" ),
	"d048" => array( "img" => "signaler.gif", "alt" => "信号" ),
	"d049" => array( "img" => "toilet.gif", "alt" => "トイレ" ),
	"d050" => array( "img" => "restaurant.gif", "alt" => "レストラン" ),
	"d051" => array( "img" => "cafe.gif", "alt" => "喫茶店" ),
	"d052" => array( "img" => "bar.gif", "alt" => "バー (マティーニ)" ),
	"d053" => array( "img" => "beer.gif", "alt" => "ビール" ),
	"d054" => array( "img" => "fastfood.gif", "alt" => "ファーストフード (ハンバーガー)" ),
	"d055" => array( "img" => "boutique.gif", "alt" => "ブティック" ),
	"d056" => array( "img" => "hairsalon.gif", "alt" => "美容院 (鋏)" ),
	"d057" => array( "img" => "karaoke.gif", "alt" => "カラオケ" ),
	"d058" => array( "img" => "movie.gif", "alt" => "映画" ),
	"d059" => array( "img" => "upwardright.gif", "alt" => "右斜め上" ),
	"d060" => array( "img" => "carouselpony.gif", "alt" => "遊園地 (木馬)" ),
	"d061" => array( "img" => "music.gif", "alt" => "音楽 (ヘッドホン)" ),
	"d062" => array( "img" => "art.gif", "alt" => "アート" ),
	"d063" => array( "img" => "drama.gif", "alt" => "演劇" ),
	"d064" => array( "img" => "event.gif", "alt" => "イベント (サーカス)" ),
	"d065" => array( "img" => "ticket.gif", "alt" => "チケット" ),
	"d066" => array( "img" => "smoking.gif", "alt" => "喫煙" ),
	"d067" => array( "img" => "nosmoking.gif", "alt" => "禁煙" ),
	"d068" => array( "img" => "camera.gif", "alt" => "カメラ" ),
	"d069" => array( "img" => "bag.gif", "alt" => "カバン" ),
	"d070" => array( "img" => "book.gif", "alt" => "本" ),
	"d071" => array( "img" => "ribbon.gif", "alt" => "リボン" ),
	"d072" => array( "img" => "present.gif", "alt" => "プレゼント" ),
	"d073" => array( "img" => "birthday.gif", "alt" => "バースデー" ),
	"d074" => array( "img" => "telephone.gif", "alt" => "電話" ),
	"d075" => array( "img" => "mobilephone.gif", "alt" => "携帯電話" ),
	"d076" => array( "img" => "memo.gif", "alt" => "メモ" ),
	"d077" => array( "img" => "tv.gif", "alt" => "TV" ),
	"d078" => array( "img" => "game.gif", "alt" => "ゲーム" ),
	"d079" => array( "img" => "cd.gif", "alt" => "CD" ),
	"d080" => array( "img" => "heart.gif", "alt" => "ハート" ),
	"d081" => array( "img" => "spade.gif", "alt" => "スペード" ),
	"d082" => array( "img" => "diamond.gif", "alt" => "ダイヤ" ),
	"d083" => array( "img" => "club.gif", "alt" => "クラブ" ),
	"d084" => array( "img" => "eye.gif", "alt" => "目" ),
	"d085" => array( "img" => "ear.gif", "alt" => "耳" ),
	"d086" => array( "img" => "rock.gif", "alt" => "手 (グー)" ),
	"d087" => array( "img" => "scissors.gif", "alt" => "手 (チョキ)" ),
	"d088" => array( "img" => "paper.gif", "alt" => "手 (パー)" ),
	"d089" => array( "img" => "downwardright.gif", "alt" => "右斜め下" ),
	"d090" => array( "img" => "upwardleft.gif", "alt" => "左斜め上" ),
	"d091" => array( "img" => "foot.gif", "alt" => "足" ),
	"d092" => array( "img" => "shoe.gif", "alt" => "くつ" ),
	"d093" => array( "img" => "eyeglass.gif", "alt" => "眼鏡" ),
	"d094" => array( "img" => "wheelchair.gif", "alt" => "車椅子" ),
	"d095" => array( "img" => "newmoon.gif", "alt" => "新月" ),
	"d096" => array( "img" => "moon1.gif", "alt" => "やや欠け月" ),
	"d097" => array( "img" => "moon2.gif", "alt" => "半月" ),
	"d098" => array( "img" => "moon3.gif", "alt" => "三日月" ),
	"d099" => array( "img" => "fullmoon.gif", "alt" => "満月" ),
	"d100" => array( "img" => "dog.gif", "alt" => "犬" ),
	"d101" => array( "img" => "cat.gif", "alt" => "猫" ),
	"d102" => array( "img" => "yacht.gif", "alt" => "リゾート (ヨット)" ),
	"d103" => array( "img" => "xmas.gif", "alt" => "クリスマス" ),
	"d104" => array( "img" => "downwardleft.gif", "alt" => "左斜め下" ),
	"d105" => array( "img" => "phoneto.gif", "alt" => "phone to" ),
	"d106" => array( "img" => "mailto.gif", "alt" => "mail to" ),
	"d107" => array( "img" => "faxto.gif", "alt" => "fax to" ),
	"d108" => array( "img" => "info01.gif", "alt" => "iモード" ),
	"d109" => array( "img" => "info02.gif", "alt" => "iモード (枠付き)" ),
	"d110" => array( "img" => "mail.gif", "alt" => "メール" ),
	"d111" => array( "img" => "by-d.gif", "alt" => "ドコモ提供" ),
	"d112" => array( "img" => "d-point.gif", "alt" => "ドコモポイント" ),
	"d113" => array( "img" => "yen.gif", "alt" => "有料" ),
	"d114" => array( "img" => "free.gif", "alt" => "無料" ),
	"d115" => array( "img" => "id.gif", "alt" => "ID" ),
	"d116" => array( "img" => "key.gif", "alt" => "パスワード" ),
	"d117" => array( "img" => "enter.gif", "alt" => "次項有" ),
	"d118" => array( "img" => "clear.gif", "alt" => "クリア" ),
	"d119" => array( "img" => "search.gif", "alt" => "サーチ (調べる)" ),
	"d120" => array( "img" => "new.gif", "alt" => "NEW" ),
	"d121" => array( "img" => "flag.gif", "alt" => "位置情報" ),
	"d122" => array( "img" => "free.gif", "alt" => "フリーダイヤル" ),
	"d123" => array( "img" => "sharp.gif", "alt" => "シャープダイヤル" ),
	"d124" => array( "img" => "mobaq.gif", "alt" => "モバQ" ),
	"d125" => array( "img" => "one.gif", "alt" => "1 (one)" ),
	"d126" => array( "img" => "two.gif", "alt" => "2 (two)" ),
	"d127" => array( "img" => "three.gif", "alt" => "3 (three)" ),
	"d128" => array( "img" => "four.gif", "alt" => "4 (four)" ),
	"d129" => array( "img" => "five.gif", "alt" => "5 (five)" ),
	"d130" => array( "img" => "six.gif", "alt" => "6 (six)" ),
	"d131" => array( "img" => "seven.gif", "alt" => "7 (seven)" ),
	"d132" => array( "img" => "eight.gif", "alt" => "8 (eight)" ),
	"d133" => array( "img" => "nine.gif", "alt" => "9 (nine)" ),
	"d134" => array( "img" => "zero.gif", "alt" => "0 (zero)" ),
	"d135" => array( "img" => "ok.gif", "alt" => "決定 (OK)" ),
	"d136" => array( "img" => "heart01.gif", "alt" => "黒ハート" ),
	"d137" => array( "img" => "heart02.gif", "alt" => "揺れるハート" ),
	"d138" => array( "img" => "heart03.gif", "alt" => "失恋" ),
	"d139" => array( "img" => "heart04.gif", "alt" => "ハートたち (複数ハート)" ),
	"d140" => array( "img" => "happy01.gif", "alt" => "わーい (嬉しい顔)" ),
	"d141" => array( "img" => "angry.gif", "alt" => "ちっ (怒った顔)" ),
	"d142" => array( "img" => "despair.gif", "alt" => "がく〜 (落胆した顔)" ),
	"d143" => array( "img" => "sad.gif", "alt" => "もうやだ〜 (悲しい顔)" ),
	"d144" => array( "img" => "wobbly.gif", "alt" => "ふらふら" ),
	"d145" => array( "img" => "up.gif", "alt" => "グッド (上向き矢印)" ),
	"d146" => array( "img" => "note.gif", "alt" => "るんるん (音符)" ),
	"d147" => array( "img" => "spa.gif", "alt" => "いい気分 (温泉)" ),
	"d148" => array( "img" => "cute.gif", "alt" => "かわいい" ),
	"d149" => array( "img" => "kissmark.gif", "alt" => "キスマーク" ),
	"d150" => array( "img" => "shine.gif", "alt" => "ぴかぴか (新しい)" ),
	"d151" => array( "img" => "flair.gif", "alt" => "ひらめき" ),
	"d152" => array( "img" => "annoy.gif", "alt" => "むかっ (怒り)" ),
	"d153" => array( "img" => "punch.gif", "alt" => "パンチ" ),
	"d154" => array( "img" => "bomb.gif", "alt" => "爆弾" ),
	"d155" => array( "img" => "notes.gif", "alt" => "ムード" ),
	"d156" => array( "img" => "down.gif", "alt" => "バッド (下向き矢印)" ),
	"d157" => array( "img" => "sleepy.gif", "alt" => "眠い (睡眠)" ),
	"d158" => array( "img" => "sign01.gif", "alt" => "exclamation" ),
	"d159" => array( "img" => "sign02.gif", "alt" => "exclamation and question" ),
	"d160" => array( "img" => "sign03.gif", "alt" => "double exclamation" ),
	"d161" => array( "img" => "impact.gif", "alt" => "どんっ (衝撃)" ),
	"d162" => array( "img" => "sweat01.gif", "alt" => "あせあせ (飛び散る汗)" ),
	"d163" => array( "img" => "sweat02.gif", "alt" => "たらーっ (汗)" ),
	"d164" => array( "img" => "dash.gif", "alt" => "ダッシュ (走り出すさま)" ),
	"d165" => array( "img" => "sign04.gif", "alt" => "ー (長音記号1)" ),
	"d166" => array( "img" => "sign05.gif", "alt" => "ー (長音記号2)" ),
	"d167" => array( "img" => "slate.gif", "alt" => "カチンコ" ),
	"d168" => array( "img" => "pouch.gif", "alt" => "ふくろ" ),
	"d169" => array( "img" => "pen.gif", "alt" => "ペン" ),
	"d170" => array( "img" => "shadow.gif", "alt" => "人影" ),
	"d171" => array( "img" => "chair.gif", "alt" => "いす" ),
	"d172" => array( "img" => "night.gif", "alt" => "夜" ),
	"d173" => array( "img" => "soon.gif", "alt" => "soon" ),
	"d174" => array( "img" => "on.gif", "alt" => "on" ),
	"d175" => array( "img" => "end.gif", "alt" => "end" ),
	"d176" => array( "img" => "clock.gif", "alt" => "時計" ),
	"d201" => array( "img" => "appli01.gif", "alt" => "iアプリ" ),
	"d202" => array( "img" => "appli02.gif", "alt" => "iアプリ (枠付き)" ),
	"d203" => array( "img" => "t-shirt.gif", "alt" => "Tシャツ (ボーダー)" ),
	"d204" => array( "img" => "moneybag.gif", "alt" => "がま口財布" ),
	"d205" => array( "img" => "rouge.gif", "alt" => "化粧" ),
	"d206" => array( "img" => "denim.gif", "alt" => "ジーンズ" ),
	"d207" => array( "img" => "snowboard.gif", "alt" => "スノボ" ),
	"d208" => array( "img" => "bell.gif", "alt" => "チャペル" ),
	"d209" => array( "img" => "door.gif", "alt" => "ドア" ),
	"d210" => array( "img" => "dollar.gif", "alt" => "ドル袋" ),
	"d211" => array( "img" => "pc.gif", "alt" => "パソコン" ),
	"d212" => array( "img" => "loveletter.gif", "alt" => "ラブレター" ),
	"d213" => array( "img" => "wrench.gif", "alt" => "レンチ" ),
	"d214" => array( "img" => "pencil.gif", "alt" => "鉛筆" ),
	"d215" => array( "img" => "crown.gif", "alt" => "王冠" ),
	"d216" => array( "img" => "ring.gif", "alt" => "指輪" ),
	"d217" => array( "img" => "sandclock.gif", "alt" => "砂時計" ),
	"d218" => array( "img" => "bicycle.gif", "alt" => "自転車" ),
	"d219" => array( "img" => "japanesetea.gif", "alt" => "湯のみ" ),
	"d220" => array( "img" => "watch.gif", "alt" => "腕時計" ),
	"d221" => array( "img" => "think.gif", "alt" => "考えてる顔" ),
	"d222" => array( "img" => "confident.gif", "alt" => "ほっとした顔" ),
	"d223" => array( "img" => "coldsweats01.gif", "alt" => "冷や汗 (顔)" ),
	"d224" => array( "img" => "coldsweats02.gif", "alt" => "冷や汗2 (顔)" ),
	"d225" => array( "img" => "pout.gif", "alt" => "ぷっくっくな顔" ),
	"d226" => array( "img" => "gawk.gif", "alt" => "ボケーっとした顔" ),
	"d227" => array( "img" => "lovely.gif", "alt" => "目がハート (顔)" ),
	"d228" => array( "img" => "good.gif", "alt" => "指でOK" ),
	"d229" => array( "img" => "bleah.gif", "alt" => "あっかんべー" ),
	"d230" => array( "img" => "wink.gif", "alt" => "ウィンク" ),
	"d231" => array( "img" => "happy02.gif", "alt" => "うれしい顔" ),
	"d232" => array( "img" => "bearing.gif", "alt" => "がまん顔" ),
	"d233" => array( "img" => "catface.gif", "alt" => "猫2" ),
	"d234" => array( "img" => "crying.gif", "alt" => "泣き顔" ),
	"d235" => array( "img" => "weep.gif", "alt" => "涙" ),
	"d236" => array( "img" => "ng.gif", "alt" => "NG" ),
	"d237" => array( "img" => "clip.gif", "alt" => "クリップ" ),
	"d238" => array( "img" => "copyright.gif", "alt" => "コピーライト (C)" ),
	"d239" => array( "img" => "tm.gif", "alt" => "トレードマーク (TM)" ),
	"d240" => array( "img" => "run.gif", "alt" => "走る人" ),
	"d241" => array( "img" => "secret.gif", "alt" => "マル秘" ),
	"d242" => array( "img" => "recycle.gif", "alt" => "リサイクル" ),
	"d243" => array( "img" => "r-mark.gif", "alt" => "レジスタードトレードマーク (R)" ),
	"d244" => array( "img" => "danger.gif", "alt" => "危険・警告 (!)" ),
	"d245" => array( "img" => "ban.gif", "alt" => "禁止" ),
	"d246" => array( "img" => "empty.gif", "alt" => "空室・空席・空車" ),
	"d247" => array( "img" => "pass.gif", "alt" => "合格マーク" ),
	"d248" => array( "img" => "full.gif", "alt" => "満室・満席・満車" ),
	"d249" => array( "img" => "leftright.gif", "alt" => "矢印左右" ),
	"d250" => array( "img" => "updown.gif", "alt" => "矢印上下" ),
	"d251" => array( "img" => "school.gif", "alt" => "学校" ),
	"d252" => array( "img" => "wave.gif", "alt" => "波" ),
	"d253" => array( "img" => "fuji.gif", "alt" => "富士山" ),
	"d254" => array( "img" => "clover.gif", "alt" => "クローバー" ),
	"d255" => array( "img" => "cherry.gif", "alt" => "さくらんぼ" ),
	"d256" => array( "img" => "tulip.gif", "alt" => "チューリップ" ),
	"d257" => array( "img" => "banana.gif", "alt" => "バナナ" ),
	"d258" => array( "img" => "apple.gif", "alt" => "りんご" ),
	"d259" => array( "img" => "bud.gif", "alt" => "芽" ),
	"d260" => array( "img" => "maple.gif", "alt" => "もみじ" ),
	"d261" => array( "img" => "cherryblossom.gif", "alt" => "桜" ),
	"d262" => array( "img" => "riceball.gif", "alt" => "おにぎり" ),
	"d263" => array( "img" => "cake.gif", "alt" => "ショートケーキ" ),
	"d264" => array( "img" => "bottle.gif", "alt" => "とっくり (おちょこ付き)" ),
	"d265" => array( "img" => "noodle.gif", "alt" => "どんぶり" ),
	"d266" => array( "img" => "bread.gif", "alt" => "パン" ),
	"d267" => array( "img" => "snail.gif", "alt" => "かたつむり" ),
	"d268" => array( "img" => "chick.gif", "alt" => "ひよこ" ),
	"d269" => array( "img" => "penguin.gif", "alt" => "ペンギン" ),
	"d270" => array( "img" => "fish.gif", "alt" => "魚" ),
	"d271" => array( "img" => "delicious.gif", "alt" => "うまい! (顔)" ),
	"d272" => array( "img" => "smile.gif", "alt" => "ウッシッシ (顔)" ),
	"d273" => array( "img" => "horse.gif", "alt" => "ウマ" ),
	"d274" => array( "img" => "pig.gif", "alt" => "ブタ" ),
	"d275" => array( "img" => "wine.gif", "alt" => "ワイングラス" ),
	"d276" => array( "img" => "shock.gif", "alt" => "げっそり (顔)" ),
);
